---
# SAST: Erlang Pest https://github.com/okeuday/pest
- id: pest
  name: SAST:pest - Erlang Security Testing (via Docker build)
  description: Run PEST SAST for Erlang (via Docker build)
  language: docker
  files: "[.]erl$"
  entry: "/pest/pest.erl"
  args: ["-ev"]
